Repository wecode-bootcamp-korea/30-westagram-backend-4-team, pull requests merged in 2022-02, with the labels that each got.

#4 [김산]mission 1 : Django 초기 세팅
  students/kimSan/.gitignore
  students/kimSan/manage.py
  students/kimSan/requirements.txt
  students/kimSan/westagram/__init__.py
  students/kimSan/westagram/asgi.py
  students/kimSan/westagram/settings.py
  students/kimSan/westagram/urls.py
  students/kimSan/westagram/wsgi.py
Labels: 멘토 리뷰 요청

#5 [김산] Mission 2: 모델링
  students/kimSan/.gitignore
  students/kimSan/manage.py
  students/kimSan/requirements.txt
  students/kimSan/westagram/__init__.py
  students/kimSan/westagram/asgi.py
  students/kimSan/westagram/settings.py
  students/kimSan/westagram/urls.py
  students/kimSan/westagram/wsgi.py
Labels: 멘토 리뷰 요청

#2 [안성준] Mission 1 : Django 초기 세팅
  students/sungjoon/.gitignore
  students/sungjoon/manage.py
  students/sungjoon/requirements.txt
  students/sungjoon/westagram/__init__.py
  students/sungjoon/westagram/asgi.py
  students/sungjoon/westagram/settings.py
  students/sungjoon/westagram/urls.py
  students/sungjoon/westagram/wsgi.py
Labels: 멘토 리뷰 요청

#3 [박건규] Mission 1: Django 초기 세팅
  students/geongue/.gitignore
  students/geongue/manage.py
  students/geongue/requirements.txt
  students/geongue/westagram/__init__.py
  students/geongue/westagram/asgi.py
  students/geongue/westagram/settings.py
  students/geongue/westagram/urls.py
  students/geongue/westagram/wsgi.py
Labels: 멘토 리뷰 요청

#10 [김산] Mission 1: Django 초기 세팅
  students/kimsan/manage.py
  students/kimsan/requirements.txt
  students/kimsan/westagram/__init__.py
  students/kimsan/westagram/asgi.py
  students/kimsan/westagram/settings.py
  students/kimsan/westagram/urls.py
  students/kimsan/westagram/wsgi.py
Labels: 멘토 리뷰 요청

#7 [김기현] Mission 2: 모델링
  students/kihyeon/config/settings.py
  students/kihyeon/config/urls.py
  students/kihyeon/users/__init__.py
  students/kihyeon/users/admin.py
  students/kihyeon/users/apps.py
  students/kihyeon/users/migrations/0001_initial.py
  students/kihyeon/users/migrations/0002_alter_userinformation_phone_number.py
  students/kihyeon/users/migrations/0003_userinformation_created_at_and_more.py
  students/kihyeon/users/migrations/0004_alter_userinformation_phone_number.py
  students/kihyeon/users/migrations/0005_rename_name_userinformation_first_name_and_more.py
  students/kihyeon/users/migrations/__init__.py
  students/kihyeon/users/models.py
  students/kihyeon/users/tests.py
  students/kihyeon/users/urls.py
  students/kihyeon/users/views.py
Labels: 멘토 리뷰 요청, 수정 요청

#12 [박건규] Mission 2: 모델링
  students/geongue/users/__init__.py
  students/geongue/users/admin.py
  students/geongue/users/apps.py
  students/geongue/users/migrations/0001_initial.py
  students/geongue/users/migrations/__init__.py
  students/geongue/users/models.py
  students/geongue/users/tests.py
  students/geongue/users/views.py
  students/geongue/westagram/settings.py
Labels: 멘토 리뷰 요청, 수정 요청

#15 [김기현] Mission 3: 회원가입 기능 구현
  students/kihyeon/.vscode/settings.json
  students/kihyeon/Pipfile
  students/kihyeon/Pipfile.lock
  students/kihyeon/config/settings.py
  students/kihyeon/config/urls.py
  students/kihyeon/users/migrations/0006_user_delete_userinformation.py
  students/kihyeon/users/migrations/0007_alter_user_table.py
  students/kihyeon/users/migrations/0008_alter_user_password_alter_user_table.py
  students/kihyeon/users/migrations/0009_alter_user_phone_number.py
  students/kihyeon/users/models.py
  students/kihyeon/users/urls.py
  students/kihyeon/users/validators.py
  students/kihyeon/users/views.py
Labels: 멘토 리뷰 요청

#18 [안성준] Mission 3: 회원가입 기능 구현
  students/sungjoon/users/urls.py
  students/sungjoon/users/validations.py
  students/sungjoon/users/views.py
  students/sungjoon/westagram/urls.py
Labels: 멘토 리뷰 요청

#16 [박건규] Mission 3 : 회원가입 기능 구현
  students/geongue/users/migrations/0002_rename_name_user_first_name_user_created_at_and_more.py
  students/geongue/users/migrations/0003_remove_user_username.py
  students/geongue/users/migrations/0004_alter_user_last_name.py
  students/geongue/users/urls.py
  students/geongue/users/validations.py
  students/geongue/users/views.py
  students/geongue/westagram/urls.py
Labels: 멘토 리뷰 요청, 수정 요청

#21 [박건규] Mission 4: 로그인 기능 구현
  students/geongue/users/urls.py
  students/geongue/users/views.py
Labels: 완료

#19 [김기현] Mission 4: 로그인 기능 구현
  students/kihyeon/users/urls.py
  students/kihyeon/users/views.py
Labels: 멘토 리뷰 요청

#17 [김산] Mission 3: 회원가입 기능 구현
  students/kimsan/users/migrations/0001_initial.py
  students/kimsan/users/models.py
  students/kimsan/users/urls.py
  students/kimsan/users/validation.py
  students/kimsan/users/views.py
  students/kimsan/westagram/settings.py
  students/kimsan/westagram/urls.py
Labels: 멘토 리뷰 요청, 수정 요청

#23 [김산] Mission 4: 로그인 기능 구현
  students/kimsan/users/urls.py
  students/kimsan/users/views.py
Labels: 멘토 리뷰 요청, 피어 리뷰 완료

#20 [안성준] Mission 4: 로그인 기능 구현
  students/sungjoon/users/urls.py
  students/sungjoon/users/views.py
Labels: 멘토 리뷰 요청

#27 [김기현] Add : null True in phone_number
  students/kihyeon/users/migrations/0010_alter_user_phone_number.py
  students/kihyeon/users/migrations/0011_alter_user_created_at_alter_user_last_name_and_more.py
  students/kihyeon/users/models.py
Labels: 수정 요청

#28 [박건규] Mission 5: 회원가입 비밀번호 암호화 적용
  students/geongue/users/migrations/0005_alter_user_phone.py
  students/geongue/users/models.py
Labels: 멘토 리뷰 요청, 피어 리뷰 완료

#25 [김산] Mission 5: 회원가입 비밀번호 암호화 적용
  students/kimsan/users/migrations/0002_alter_user_password.py
  students/kimsan/users/migrations/0003_alter_user_phone_number.py
  students/kimsan/users/migrations/0004_alter_user_extra_information_alter_user_phone_number.py
  students/kimsan/users/models.py
  students/kimsan/users/validation.py
  students/kimsan/users/views.py
Labels: 멘토 리뷰 요청

#22 [김기현] Mission 5: 회원가입 비밀번호 암호화 적용
  students/kihyeon/Pipfile
  students/kihyeon/Pipfile.lock
  students/kihyeon/users/migrations/0010_alter_user_phone_number.py
  students/kihyeon/users/migrations/0011_alter_user_created_at_alter_user_last_name_and_more.py
  students/kihyeon/users/views.py
Labels: 멘토 리뷰 요청

#29 [김기현] Mission 6: 로그인 JWT 발급
  students/kihyeon/Pipfile
  students/kihyeon/users/views.py
Labels: 멘토 리뷰 요청

#26 [안성준] Mission 5: 회원가입 비밀번호 암호화 적용
  students/sungjoon/users/models.py
  students/sungjoon/users/views.py
Labels: 멘토 리뷰 요청

#24 [박건규] Mission 5: 회원가입 비밀번호 암호화 적용
  students/geongue/users/views.py
Labels: 멘토 리뷰 요청

#30 [김산] Mission 6: 로그인 JWT 발급
  students/kimsan/users/views.py
  students/kimsan/westagram/settings.py
Labels: 멘토 리뷰 요청

#32 [안성준] Mission 6: 로그인 JWT 발급
  students/sungjoon/users/views.py
Labels: 멘토 리뷰 요청, 피어 리뷰 완료

#31 [박건규] Mission 6: 로그인 JWT 발급
  students/geongue/users/views.py
  students/geongue/westagram/settings.py
Labels: 완료
